### ISSUE TITLE
Add .gitignore file that ignores the __pycache__ directory

### ISSUE THREAD

**Issue by Anomalocaridid** [maximtrp/ranger-archives#11]
When using plugins by cloning their repos into Ranger's plugins folder, a directory named \_\_pycache__ is created. Since it is currently not ignored, git thinks that my local copy of the ranger-archives repo has been modified. This isn't a very big problem, but it is somewhat annoying and I would appreciate a .gitignore file that ignores \_\_pycache__.

**Comment by maximtrp** [comment]
Thank you for the suggestion! I have uploaded this file

**Comment by Anomalocaridid** [comment]
Thank you!
