### ISSUE TITLE
[Feature Request] Extract file to dir with the same name of the file

### ISSUE THREAD

**Issue by luiz00martins** [maximtrp/ranger-archives#13]
Currently you can "extract here" (`:extract`) and "extract to specific dir" (`:extract dir`). It'd be nice to have a variation that extracts to a folder with the same name from the original file (e.g. using it with `foo.zip` would automatically extract into a new folder called `foo`)

**Comment by maximtrp** [comment]
Hello! Thank you for suggestion! Have you tried `:extract_to_dirs`?

**Comment by luiz00martins** [comment]
Haha, indeed. Leaving it empty automatically picks the name for you.

Thank you for the answer!
