### ISSUE TITLE
Can't unrar

### ISSUE THREAD

**Issue by rafli-sss** [maximtrp/ranger-archives#18]
Does this not work on rar format?
If i run "ranger --debug" and unrar the file, ranger crashed.
![Screenshot from 2022-09-05 20-37-24](https://user-images.githubusercontent.com/92916692/188463350-3e44e83d-f3c5-4176-a270-50bdff1ce3c9.png)

**Comment by maximtrp** [comment]
Thank you for reporting! I rarely decompress `rar` archives, so the support was poor. I added support for `7z` and `unrar`. You should have them installed in your system.
