### ISSUE TITLE
extract_to_dirs creates a folder with a wrong name due to incorrect archive name split

### ISSUE THREAD

**Issue by zaiqiang-dong** [maximtrp/ranger-archives#19]
extrack_to_dir  is a very good function，but a small problem is dir name. when i  run "extrack_to_dir aaa.bbb.zip", will create a dir named aaa, but correctly is aaa.bbb.

**Comment by bzglve** [comment]
I also ran into this
![image](https://user-images.githubusercontent.com/35001580/215886208-8976ab42-2c34-409d-beb1-f7ba4830cddf.png)
![image](https://user-images.githubusercontent.com/35001580/215886256-f0b43918-9e59-4004-8b46-5e95ed702467.png)
