### ISSUE TITLE
extract_to_dirs does not work with .tar.gz files

### ISSUE THREAD

**Issue by tugurio** [maximtrp/ranger-archives#2]
Hi. I don't know if the problem is only with that format, but with zip everything works fine. However, using `extract_to_dirs` with .tar.gz and .tgz return an error and nothing get extracted. Using `extract` however works without any problem.
The error is `aunpack: tar ...:non-zero return-code`

**Comment by maximtrp** [comment]
Thank you for reporting. There was a bug in `:extract` too. Somehow `aunpack` does not create directories for `tar` archives when extracting with a specified dir name. Anyway I have implemented a workaround. It should be working now
