### ISSUE TITLE
compressing some files with a totally large size into a 7z makes ranger freeze

### ISSUE THREAD

**Issue by rockyzhang24** [maximtrp/ranger-archives#3]
Hello,

I have some images under a folder shown below:
![image](https://user-images.githubusercontent.com/11582667/104938839-7b969580-5964-11eb-8fa0-72660b0c62a2.png)

Then, I selected all the images by `v`, and tried to compress them into a 7z file by `:compress image.7z`. I saw `image.7z` file appeared (its size was very small, and it seems that the compressing had not finished yet) but ranger gets frozen and `\` symbol on the top right corner stopped spinning and is stuck there. I have to close my terminal window forcedly. A screenshot is attached below.
![image](https://user-images.githubusercontent.com/11582667/104939349-29a23f80-5965-11eb-9c40-fe7bbfefd87c.png)

system information:
macOS: Big Sur 11.1
ranger: the lastest master (built from the master)

Thank you very much.

**Comment by maximtrp** [comment]
Hey! Thank you for the report. But I cannot replicate your bug, my ranger is working correctly. Do you have [p7zip](https://formulae.brew.sh/formula/p7zip) installed?

**Comment by rockyzhang24** [comment]
Thank you for your quick response. I am not sure whether this bug is related to the OS, i.e., macOS. Are you running ranger on macOS, or Linux? Other than this, I have some other little bugs for ranger which only occur on macOS. 

> Do you have p7zip installed

Of course. I have all the pre-requisites installed on my system (installing them via `brew`). And I can use `atool` to compress these image files into 7z in the terminal directly. I attached a screenshot showing the result below.
![image](https://user-images.githubusercontent.com/11582667/104947647-efd73600-5970-11eb-9b01-54067788992c.png)

Even though it works well, you could see that it shows "Wide character in setenv at /usr/local/bin/atool line 33" on the first line of the result. I have no idea about it but I believe it resides on atool itself and it will not affect atool's functionalities (like a warning somehow). 

In ranger, by using your compress code, even though compressing into 7z make it stuck, compressing into other formats like zip or tar.gz works well. 

Currently, I run `atool` directly in ranger to compress files like this way `map ,c console -p15 shell -p atool  -a -E %s`

**Comment by maximtrp** [comment]
Thank you for the detailed comments! Yes, I'm running Linux on almost all of my machines and do not have any bugs with this plugin. I will test it on my iMac.

**Comment by rockyzhang24** [comment]
Great. Thank you very much.

**Comment by maximtrp** [comment]
I have managed to reproduce this bug. It is unclear what is causing it, but I will try to fix or somehow refactor the code.

**Comment by maximtrp** [comment]
I have completely rewritten the plugin and got rid of `atool` dependency, but the problem persists. The other archivers seem to be working well under MacOS.
