### ISSUE TITLE
Error while loading plugin 'compress'

### ISSUE THREAD

**Issue by duffydack** [maximtrp/ranger-archives#4]
Seems after the compress update commit ef747ea3daf59bc8abc44a19b7d6e931803e2e22, copying compress.py to plugins folder, or using make install, running ranger afterward gives error 'Error while loading plugin 'compress'.

Copying archives_utils.py to plugins folder fixes it.

**Comment by maximtrp** [comment]
Thanks for reporting! I have uploaded the fix today, so it should be working.
