### ISSUE TITLE
I have a Error when using `:extract` to uncompress archieves. 

### ISSUE THREAD

**Issue by nations-Xiong** [maximtrp/ranger-archives#5]
This is an animation: [https://gitee.com/nations-Xiong/typora-images/raw/master/test_ranger.svg](https://gitee.com/nations-Xiong/typora-images/raw/master/test_ranger.svg)

**Comment by maximtrp** [comment]
Thanks for reporting! I have pushed a fix.

**Comment by nations-Xiong** [comment]
> Thanks for reporting! I have pushed a fix.

Thanks for your work.
