### ISSUE TITLE
Create an __init__.py file as an entry point to simplify installation and updating

### ISSUE THREAD

**Issue by Anomalocaridid** [maximtrp/ranger-archives#6]
Ranger at some point added the ability to load plugins from directories inside the plugin folder. However, this requires a file named `__init__.py` to use a an entry point. This would simplify installation and updating by allowing users to simply clone the ranger-archives repository to the plugin folder and eliminate the need to copy files to the plugin folder every time this plugin gets updated.

**Comment by maximtrp** [comment]
Thank you! I have created a directory with the plugin files (`ranger-archives`). Now you can just clone/copy it.

**Comment by Anomalocaridid** [comment]
Putting it in its own directory defeats the purpose, as it will already be in a directory when someone clones the git repo. And I don't think ranger would know to look in the sub-directory.

Edit: Just to clear up, when I said the "plugin folder," I meant the folder that you put ranger plugins in to install them.
