### ISSUE TITLE
Move the plugin files back out of the ranger-archives folder to simplify installation and updating

### ISSUE THREAD

**Issue by Anomalocaridid** [maximtrp/ranger-archives#7]
With the \_\_init__.py file added in #6, this would allow people to simply use git to clone the repository into ranger's plugin folder without needing to worry about copying things manually. This would also simplify updating the plugin by reducing the updating steps to a single `git pull` command without worrying about any changes in files to copy over.

Currently the steps for installing/updating are as follows:
1. Clone the git repository/pull any changes to the local repository
2. Copy the ranger-archives folder to ranger's plugin folder

This change would make it so that users only need to perform one step: cloning the git repository into the ranger plugins folder.

**Comment by maximtrp** [comment]
I should have done this before. Thank you again! Repo can now be safely cloned to `plugins` folder.

**Comment by Anomalocaridid** [comment]
Thank you!
