### ISSUE TITLE
Error while loading plugin 'ranger-archives'

### ISSUE THREAD

**Issue by manujchandra** [maximtrp/ranger-archives#8]
![Screenshot from 2021-06-08 20-51-00](https://user-images.githubusercontent.com/15191493/121212872-5d8deb00-c89b-11eb-95fb-3e77585b29cf.png)

ranger version: ranger 1.9.3

Python version: 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]

Locale: en_US.UTF-8

**Comment by maximtrp** [comment]
Thank you for reporting this. Fixed in the latest commit. Please update with `git pull`.
