### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by manujchandra** [maximtrp/ranger-archives#9]
Hi,

When we compress something in gnome, we can see time remaining and progress of compression.

If there a way to see that when using this plugin?

Also, what can we use in flags?

Thanks.

**Comment by maximtrp** [comment]
Hello! I will see what I can do with the progress. You can use flags with your archivers or compression tools just as you normally would do it in the terminal. I will add some examples to README

**Comment by manujchandra** [comment]
Hi This issue was closed. Was this implemented?

Also, could you please refer to some resources to learn about CommandLoader or how to show the progress of a command in the task view?

For example, I want to use PyCP to copy a file, but I want to show the copy progress bar in the task view. Is this possible?

Any help is appropriated.

Thanks.

**Comment by maximtrp** [comment]
Hello!

I have added some examples of using flags to `README` file, but I have no idea of how to implement progress bar for compressing files. You can read about `CommandLoader` [here](https://github.com/ranger/ranger/blob/master/ranger/core/loader.py#L150). I have found that [these lines](https://github.com/ranger/ranger/blob/277e1db745a817f522278487b97f1518b54d668e/ranger/gui/widgets/statusbar.py#L331) are related to drawing progress bars in ranger.

> For example, I want to use PyCP to copy a file, but I want to show the copy progress bar in the task view. Is this possible?

Progress bar for copying is already implemented in ranger. I think it is possible. Just look at the code in ranger repo that I refer to.
